In [1]:
import numpy as np
import pandas as pd

In [2]:
meta_map = pd.read_csv('../data/ibd/meta_map.txt', sep = '\t', skiprows = 1)
id_to_meta = pd.Series(meta_map['Exact Match to Standard (* = isomer family)'].values,index=meta_map['Metabolomic Feature']).to_dict()

In [3]:
meta_raw = pd.read_csv('../data/ibd/meta_raw.txt', sep = '\t', skiprows=1)
keep_cols = [c for c in meta_raw.columns if c.split('|')[0] == 'PRISM']
meta_raw['# Feature / Sample'] = meta_raw['# Feature / Sample'].map(id_to_meta)
meta_raw = meta_raw.dropna(how='any')
df_meta = meta_raw.set_index('# Feature / Sample')
df_meta = df_meta[keep_cols]
df_meta = df_meta.T
# 390 unique, 468 or so prior
df_meta = df_meta.groupby(lambda x:x, axis=1).sum()
df_meta.head()
df_meta.to_csv('../data/ibd/df_meta.txt', sep = '\t')

In [5]:
otu_raw = pd.read_csv('../data/ibd/otu_raw.txt', sep = '\t', skiprows = 1)
keep_cols = [c for c in otu_raw.columns if c.split('|')[0] == 'PRISM']
df_otu = otu_raw.set_index('# Feature / Sample')
df_otu = df_otu[keep_cols]
#nonzero_min = df_otu[ df_otu != 0 ].min()/2
#for col in df_otu.columns.values:
#    df_otu[col] = df_otu[col].replace(0,nonzero_min[col])
#df_otu = np.log(df_otu)
df_otu = df_otu.T
df_otu.head()
df_otu.to_csv('../data/ibd/df_otu.txt', sep = '\t')

In [6]:
rdf = pd.read_csv('../data_analysis/cutie_ibd_rsc1fdr0.05/data_processing/R_matrix_L6rev_resample_1.txt', sep = '\t')
FN_df = rdf[rdf['indicators'] == 1]
TN_df = rdf[rdf['indicators'] == -1]
FN_df.head()

,var1_index,var2_index,avg_var1,avg_var2,var_var1,var_var2,pvalues,logpvals,correlations,r2vals,indicators,FN_rev_indicators,TN_rev_indicators,extreme_p,extreme_r,p_ratio,r2_ratio,Unnamed: 17
25,0.0,25.0,0.00441,120.946782,0.000301,28097.695338,0.009130,-4.696183,0.208788,0.208788,1.0,-1.0,-1.0,0.003386,0.234735,0.370889,1.124276,NaN
27,0.0,27.0,0.00441,200.360874,0.000301,14974.046885,0.019710,-3.926649,-0.187154,-0.187154,1.0,-1.0,-1.0,0.007941,-0.166541,0.402896,0.889859,NaN
31,0.0,31.0,0.00441,636.441018,0.000301,394055.234646,0.018553,-3.987127,-0.188932,-0.188932,1.0,-1.0,-1.0,0.005056,-0.164734,0.272511,0.871918,NaN
40,0.0,40.0,0.00441,399.267506,0.000301,179885.367657,0.015551,-4.163644,-0.194042,-0.194042,1.0,-1.0,-1.0,0.007489,-0.172807,0.481560,0.890565,NaN
47,0.0,47.0,0.00441,76.045639,0.000301,10563.391555,0.015705,-4.153752,-0.193759,-0.193759,1.0,-1.0,-1.0,0.005104,-0.178553,0.324984,0.921520,NaN

In [8]:
from collections import defaultdict
otu_names = df_otu.columns.values
print(otu_names[0:5])
meta_names = df_meta.columns.values
print(meta_names[0:5])
FN_x_to_y = defaultdict(list)
FN_var_to_p = {}
for t in otu_names:
    FN_var_to_p[t] = {}
    for m in meta_names:
        FN_var_to_p[t][m] = []

for index, row in FN_df.iterrows():
    x = otu_names[int(row['var1_index'])]
    y = meta_names[int(row['var2_index'])]
    FN_x_to_y[x].append(y)
    FN_var_to_p[x][y] = float(row['extreme_p'])

['Methanobrevibacter_smithii' 'Methanosphaera_stadtmanae'
 'Rothia_mucilaginosa' 'Propionibacterium_freudenreichii'
 'Bifidobacterium_adolescentis']
['1,2,3,4-tetrahydro-1-methyl-beta-carboline-3-carboxylic acid'
 '1,2,3,4-tetrahydro-b-carboline-1,3-dicarboxylic acid'
 '1-3-7-trimethylurate' '1-methylguanine' '1-methylnicotinamide']

In [10]:
taxa = ['Ruminococcus_navus',
'Clostridium_clostridioforme',
'Lachnospiraceae_bacterium_9_1_43BFAA',
'Enterococcus_faecium',
'Lactobacillus_gasseri',
'Blautia_producta',
'Alistipes_onderdonkii',
'Adlercreutzia_equolifaciens',
'Lachnospiraceae_bacterium_2_1_58FAA',
'Gordonibacter_pamelaeae',
'Holdemania_filiformis',
'Ruminococcus_callidus',
'Alistipes_senegalensis',
'Alistipes_indistinctus',
'Bacteroidales_bacterium_ph8',
'Eubacterium_eligens',
'Faecalibacterium_prausnitzii',
'Roseburia_intestinalis',
'Roseburia_inulinivorans',
'Alistipes_finegoldii',
'Alistipes_putredinis',
'Alistipes_shahii',
'Eubacterium_siraeum',
'Eubacterium_hallii',
'Dorea_longicatena',
'Roseburia_hominis',
'Coprococcus_catus',
'Eubacterium_ventriosum']

In [9]:
for t in taxa:
    if t in FN_x_to_y:
        print(t)
        print(len(FN_x_to_y[t]))
        for m in FN_x_to_y[t]:
            if m in metas:
                print(m)        
                x = df_otu[t]
                y = df_meta[m]
                plt.scatter(x,y)
                r, p = scipy.stats.spearmanr(x,y)
                new_p = FN_var_to_p[t][m]
                plt.savefig('../data/ibd/FN_plots/' + str(t) + '_' + str(m) + '_' +'%.3f'%(r) + '_' + '%.3f'%(p) + '_' + '%.3f'%(new_p) + '.png')
                plt.close()

NameError: name 'taxa' is not defined

In [171]:
metas = ['Linoleic acid',
'C54:4 TAG*',
'caprylic acid',
'carnosol',
'cyclomethyltryptophan*',
'geranyl acetoacetate*',
'urobilin*',
'pipecolic acid',
'pyridoxamine',
'thiamine',
'4-methylcatechol',
'2-hydroxyhexadecanoate',
'cholestenone',
'5alpha-cholestanol',
'dodecanedioic acid',
'caproic acid',
'hydrocinnamic acid',
'3-methyladipate-pimelate',
'undecanedionate',
'azelaic acid',
'2-hydroxyphenethylamine',
'linoleoyl ethanolamide',
'palmitoylethanolamide',
'docosapentaenoic acid',
'eicosatrienoic acid',
'taurine',
'N-acetylputrescine',
'ADMA',
'Cholate',
'Chenodeoxycholate',
'C16 carnitine',
'C36:5 PC plasmalogen-A',
'Phytosphingosine',
'Carnitine',
'Sphingosine',
'C22:4 CE*',
'C18:0 CE',
'C20:5 CE',
'C16:0 LPC',
'Lactate',
'C14 carnitine',
'C3-DC-CH3 carnitine',
'C16:0 ceramide (d18:1)',
'C18:0e MAG',
'C22:5 CE*',
'C14:0 CE',
'Carnosine']